"""rag thesis regret tables

Revision ID: 929702cb2112
Revises: 27bff97b5d2c
Create Date: 2026-04-27 19:42:36.121639

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "929702cb2112"
down_revision: Union[str, Sequence[str], None] = "27bff97b5d2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rag_rationales",
        sa.Column("trade_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vector", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("outcome_pnl_pct", sa.Float(), nullable=False),
        sa.Column("outcome_win", sa.Boolean(), nullable=False),
        sa.Column("setup_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    op.create_index(op.f("ix_rag_rationales_symbol"), "rag_rationales", ["symbol"], unique=False)
    op.create_table(
        "regret_records",
        sa.Column("trade_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("regret", sa.Float(), nullable=False),
        sa.Column("optimal_size_pct", sa.Float(), nullable=False),
        sa.Column("actual_size_pct", sa.Float(), nullable=False),
        sa.Column("pnl_pct", sa.Float(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("setup_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    op.create_index(op.f("ix_regret_records_symbol"), "regret_records", ["symbol"], unique=False)
    op.create_table(
        "thesis_tags",
        sa.Column("trade_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tag", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("set_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thesis_tags")
    op.drop_index(op.f("ix_regret_records_symbol"), table_name="regret_records")
    op.drop_table("regret_records")
    op.drop_index(op.f("ix_rag_rationales_symbol"), table_name="rag_rationales")
    op.drop_table("rag_rationales")
    # ### end Alembic commands ###
