#!/usr/bin/env bash
# Prepare a fresh Ubuntu 24.04 server (a Hetzner Cloud box, ARM or x86) to
# run the halabot fleet. Run as root; safe to re-run, every step checks first.
#
#   ssh root@<server>
#   curl -fsSL https://raw.githubusercontent.com/lanterno/tradeHalalLLM/main/infra/server/bootstrap.sh -o bootstrap.sh
#   bash bootstrap.sh
#
# Knobs (environment): HALABOT_USER (halabot), HALABOT_DIR (/opt/halabot),
# HALABOT_REPO (the GitHub repo), TAILSCALE_AUTHKEY (optional: joins the
# tailnet unattended). What it does, and what is left to the operator after
# it, is in docs/DEPLOY.md.
set -euo pipefail

HALABOT_USER=${HALABOT_USER:-halabot}
HALABOT_DIR=${HALABOT_DIR:-/opt/halabot}
HALABOT_REPO=${HALABOT_REPO:-https://github.com/lanterno/tradeHalalLLM.git}
BACKUP_DIR=/var/backups/halabot
ETC_DIR=/etc/halabot

say() { printf '\n== %s\n' "$*"; }

[ "$(id -u)" = 0 ] || { echo "run as root" >&2; exit 1; }
# shellcheck disable=SC1091
. /etc/os-release
[ "${ID:-}" = ubuntu ] || echo "warning: written for Ubuntu 24.04, this is ${PRETTY_NAME:-unknown}" >&2
export DEBIAN_FRONTEND=noninteractive

say "packages"
apt-get update -q
apt-get upgrade -yq
apt-get install -yq ca-certificates curl git gnupg jq openssl restic ufw unattended-upgrades
if ! command -v just >/dev/null; then
    apt-get install -yq just \
        || curl -fsSL https://just.systems/install.sh | bash -s -- --to /usr/local/bin
fi
# Security updates install themselves; a reboot stays the operator's call.
printf 'APT::Periodic::Update-Package-Lists "1";\nAPT::Periodic::Unattended-Upgrade "1";\n' \
    > /etc/apt/apt.conf.d/20auto-upgrades

say "docker"
if ! command -v docker >/dev/null; then
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
        > /etc/apt/sources.list.d/docker.list
    apt-get update -q
    apt-get install -yq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
# The bots log continuously; unrotated json-file logs fill the disk in months.
if [ ! -f /etc/docker/daemon.json ]; then
    echo '{"log-driver": "json-file", "log-opts": {"max-size": "20m", "max-file": "5"}}' \
        > /etc/docker/daemon.json
    systemctl restart docker
fi
systemctl enable --now docker

say "swap"
# The image build (torch, the dashboard) peaks well above a small box's RAM.
if [ -z "$(swapon --show --noheadings)" ]; then
    fallocate -l 4G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    grep -q '^/swapfile ' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

say "firewall"
# SSH only. Docker-published ports bypass ufw, which is why the compose file
# binds every port to 127.0.0.1 rather than relying on this.
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw --force enable

say "ssh"
# Key-only logins, but only once a key is in place: never lock the operator out.
if [ -s /root/.ssh/authorized_keys ]; then
    printf 'PasswordAuthentication no\nKbdInteractiveAuthentication no\nPermitRootLogin prohibit-password\n' \
        > /etc/ssh/sshd_config.d/60-halabot.conf
    systemctl reload ssh
else
    echo "no /root/.ssh/authorized_keys: password logins left on; add a key and re-run"
fi

say "user ${HALABOT_USER}"
if ! id "$HALABOT_USER" >/dev/null 2>&1; then
    useradd --create-home --shell /bin/bash "$HALABOT_USER"
fi
usermod -aG docker "$HALABOT_USER"
home=$(getent passwd "$HALABOT_USER" | cut -d: -f6)
if [ -s /root/.ssh/authorized_keys ] && [ ! -s "$home/.ssh/authorized_keys" ]; then
    install -d -m 700 -o "$HALABOT_USER" -g "$HALABOT_USER" "$home/.ssh"
    install -m 600 -o "$HALABOT_USER" -g "$HALABOT_USER" /root/.ssh/authorized_keys "$home/.ssh/authorized_keys"
fi

say "repo ${HALABOT_DIR}"
if [ ! -d "$HALABOT_DIR/.git" ]; then
    install -d -o "$HALABOT_USER" -g "$HALABOT_USER" "$HALABOT_DIR"
    sudo -u "$HALABOT_USER" git clone -q "$HALABOT_REPO" "$HALABOT_DIR"
fi

say ".env"
env_file="$HALABOT_DIR/.env"
if [ ! -f "$env_file" ]; then
    pg_pw=$(openssl rand -hex 24)
    sed -e "s#^DATABASE_URL=.*#DATABASE_URL=postgresql+asyncpg://trader:${pg_pw}@localhost:5433/halal_trader#" \
        -e "s#^WEB_API_TOKEN=.*#WEB_API_TOKEN=$(openssl rand -hex 32)#" \
        "$HALABOT_DIR/.env.example" > "$env_file"
    printf '\n# Generated by infra/server/bootstrap.sh; the same password is in DATABASE_URL.\nPOSTGRES_PASSWORD=%s\n' \
        "$pg_pw" >> "$env_file"
    echo "wrote $env_file (fresh Postgres password and web token); fill in the API keys"
else
    echo "$env_file exists, left as is"
fi
chown "$HALABOT_USER:$HALABOT_USER" "$env_file"
chmod 600 "$env_file"

say "backups, server config"
install -d -m 750 -o "$HALABOT_USER" -g "$HALABOT_USER" "$BACKUP_DIR"
install -d -m 750 -o root -g "$HALABOT_USER" "$ETC_DIR"
if [ ! -f "$ETC_DIR/server.env" ]; then
    install -m 640 -o root -g "$HALABOT_USER" "$HALABOT_DIR/infra/server/server.env.example" "$ETC_DIR/server.env"
    echo "wrote $ETC_DIR/server.env from the example; set the backup repository and password"
fi

say "systemd units"
for unit in "$HALABOT_DIR"/infra/server/systemd/*.service "$HALABOT_DIR"/infra/server/systemd/*.timer; do
    [ -e "$unit" ] || continue
    sed -e "s#@HALABOT_DIR@#${HALABOT_DIR}#g" -e "s#@HALABOT_USER@#${HALABOT_USER}#g" \
        -e "s#@BACKUP_DIR@#${BACKUP_DIR}#g" "$unit" > "/etc/systemd/system/$(basename "$unit")"
done
systemctl daemon-reload
for timer in "$HALABOT_DIR"/infra/server/systemd/*.timer; do
    if [ -e "$timer" ]; then systemctl enable --now "$(basename "$timer")"; fi
done

say "tailscale"
if ! command -v tailscale >/dev/null; then
    curl -fsSL https://tailscale.com/install.sh | sh
fi
ufw allow in on tailscale0
if [ -n "${TAILSCALE_AUTHKEY:-}" ]; then
    tailscale up --authkey "$TAILSCALE_AUTHKEY" --hostname halabot
fi
tailscale status >/dev/null 2>&1 || echo "not on the tailnet yet: run 'tailscale up --hostname halabot'"

cat <<EOF

Done. Next (docs/DEPLOY.md has the detail):
  1. Fill in the API keys:      sudo -u ${HALABOT_USER} \$EDITOR ${env_file}
  2. Configure off-site backup:  \$EDITOR ${ETC_DIR}/server.env, then
                                 sudo -u ${HALABOT_USER} ${HALABOT_DIR}/infra/server/backup.sh --init
  3. Start the fleet:            sudo -iu ${HALABOT_USER}; cd ${HALABOT_DIR}; just build && just up && just health
  4. Dashboard on the tailnet:   tailscale serve --bg 8082
EOF
